# Site settings
baseurl = "https://chiamaka.github.io/blog"
themesDir = "./themes/"
languageCode = "en-us"
title = "Hugo Cactus Theme"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = "chiamakas-blog"

[params]
	name = "Chiamaka Nwolisa"
	description = "Describe your website"
	bio = "Writer & React Native Developer"
	# Enter optionally your twitter account
	twitter = "Mz_Chi"
	enableRSS = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = "Contact me"
  about= "About me"
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "Sometimes, I take myself too seriously! You shouldnt"
	tweet = "Tweet"
	share = "Share"
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/Mz_Chi"
    facebook = "https://www.facebook.com/chiamaka.nwolisa.3"
    github   = "https://www.github.com/Chiamaka"
